/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author morgana
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        user.setText("Olá, " + jfrLogin.getUsuarioLogado().getNome());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskArea = new javax.swing.JDesktopPane();
        user = new javax.swing.JLabel();
        barMenu = new javax.swing.JMenuBar();
        mnuCarteira = new javax.swing.JMenu();
        mnuAcoes = new javax.swing.JMenu();
        mnuUsuario = new javax.swing.JMenu();
        mnuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trader");

        dskArea.setPreferredSize(new java.awt.Dimension(900, 900));

        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setText("jLabel1");
        user.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        dskArea.setLayer(user, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dskAreaLayout = new javax.swing.GroupLayout(dskArea);
        dskArea.setLayout(dskAreaLayout);
        dskAreaLayout.setHorizontalGroup(
            dskAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskAreaLayout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        dskAreaLayout.setVerticalGroup(
            dskAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskAreaLayout.createSequentialGroup()
                .addContainerGap(477, Short.MAX_VALUE)
                .addComponent(user)
                .addContainerGap())
        );

        mnuCarteira.setText("Minha carteira");
        mnuCarteira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCarteiraMouseClicked(evt);
            }
        });
        mnuCarteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCarteiraActionPerformed(evt);
            }
        });
        barMenu.add(mnuCarteira);

        mnuAcoes.setText("Ações");
        mnuAcoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAcoesMouseClicked(evt);
            }
        });
        mnuAcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcoesActionPerformed(evt);
            }
        });
        barMenu.add(mnuAcoes);

        mnuUsuario.setText("Usuário");
        mnuUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuUsuarioMouseClicked(evt);
            }
        });
        mnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuarioActionPerformed(evt);
            }
        });
        barMenu.add(mnuUsuario);

        mnuSair.setText("Sair");
        mnuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSairMouseClicked(evt);
            }
        });
        barMenu.add(mnuSair);

        setJMenuBar(barMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dskArea, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dskArea, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void carteira(){
        IfrmCarteira carteira = new IfrmCarteira();
        dskArea.add(carteira);
        carteira.setVisible(true);
    }
    
    private void acoes(){
        IfrmAcoes acoes = new IfrmAcoes();
        dskArea.add(acoes);
        acoes.setVisible(true);
    }
    
    private void mnuCarteiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCarteiraMouseClicked
        carteira();
    }//GEN-LAST:event_mnuCarteiraMouseClicked

    private void mnuAcoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAcoesMouseClicked
        acoes();
    }//GEN-LAST:event_mnuAcoesMouseClicked

    private void mnuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSairMouseClicked
        this.dispose();
    }//GEN-LAST:event_mnuSairMouseClicked

    private void mnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioActionPerformed
        IfrmUsuario usuario = new IfrmUsuario();
        dskArea.add(usuario);
        usuario.setVisible(true);
    }//GEN-LAST:event_mnuUsuarioActionPerformed

    private void mnuUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuUsuarioMouseClicked
        IfrmUsuario usuario = new IfrmUsuario();
        dskArea.add(usuario);
        usuario.setVisible(true);
    }//GEN-LAST:event_mnuUsuarioMouseClicked

    private void mnuAcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcoesActionPerformed
        acoes();
    }//GEN-LAST:event_mnuAcoesActionPerformed

    private void mnuCarteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCarteiraActionPerformed
        carteira();
    }//GEN-LAST:event_mnuCarteiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JDesktopPane dskArea;
    private javax.swing.JMenu mnuAcoes;
    private javax.swing.JMenu mnuCarteira;
    private javax.swing.JMenu mnuSair;
    private javax.swing.JMenu mnuUsuario;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
